version: '2'

services:
  nginx:
    image: lroguet/rpi-nginx
    volumes:
      - ./www:/var/www/html
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    links:
      - php

  php:
   build: php
   volumes:
     - ./www:/var/www/html
   links:
     - db
     - influxdb

  grafana:
    image: grafana:grafana
    ports:
      - 3000:3000
    environment:
      - GF_SERVER_ROOT_URL=http://synodra.ddns.net/grafana
      - GF_SECURITY_ADMIN_PASSWORD=secret

  db:
    image: hypriot/rpi-mysql
    ports:
     - "3306:3306"
    volumes:
     - db_data2:/var/lib/mysql
    environment:
     - MYSQL_ROOT_PASSWORD=password
     - MYSQL_DATABASE=database
     - MYSQL_USER=user

   influx:
    image: influxdb:latest
    volumes:
      - ./influxdb:/var/lib/influxdb
    ports:
      - 8086:8086
      - 8083:8083

volumes:
    db_data2:
