version: '2'

services:
  nginx:
    image: lroguet/rpi-nginx
    volumes:
      - ./www:/var/www/html
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
    ports: 
      - "80:80"
    links:
      - php

  php:
   build: php
   volumes:
     - ./www:/var/www/html
   links:
     - db
   
  db:
    image: hypriot/rpi-mysql
    ports:
     - "3306:3306"
    volumes:
     - db_data2:/var/lib/mysql
    environment:
     - MYSQL_ROOT_PASSWORD=password
     - MYSQL_DATABASE=database
     - MYSQL_USER=user


volumes:
    db_data2:
